//! Conversation and message types for the chat model.
//!
//! This module defines the core data structures that represent a conversation
//! between a user and Claude. A [`Conversation`] holds an ordered list of
//! [`Message`]s and at most one [`MessageDraft`] being actively streamed.
//!
//! The key design is a **typestate** split between [`MessageDraft`] and
//! [`Message`]. While the API is streaming a response, the in-progress
//! content lives in a `MessageDraft`, which has mutable append methods.
//! Once streaming finishes, the draft is finalized into an immutable
//! `Message` via [`MessageDraft::finalize`]. This makes it impossible to
//! accidentally mutate a completed message — the type system prevents it.
//!
//! Content blocks can be plain text, tool-use requests from the model, or
//! tool results returned after execution. This matches the Anthropic Messages
//! API content block model, where a single assistant message can interleave
//! text with tool calls.
//!
//! Identifiers like [`ToolUseId`] and tool names ([`ToolName`]) are strong
//! types rather than bare strings, so the compiler catches mix-ups and
//! construction validates format invariants.

use serde::{Deserialize, Serialize};
use std::fmt;

/// Unique identifier for a tool-use request, generated by the Anthropic API.
///
/// These IDs follow the format `toolu_XXXX...` (a `toolu_` prefix followed
/// by an alphanumeric suffix). The [`ToolUseId::new`] constructor validates
/// this prefix so that malformed IDs are caught early rather than producing
/// confusing API errors downstream.
///
/// A [`ContentBlock::ToolResult`] must reference the same `ToolUseId` as
/// the [`ContentBlock::ToolUse`] it responds to.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ToolUseId(String);

impl ToolUseId {
    /// The required prefix for all Anthropic tool-use IDs.
    const PREFIX: &str = "toolu_";

    /// Create a new tool use ID, validating the `toolu_` prefix.
    ///
    /// Returns `Err` if the string doesn't start with `toolu_`.
    pub fn new(id: impl Into<String>) -> Result<Self, ToolUseIdError> {
        let id = id.into();
        if id.starts_with(Self::PREFIX) {
            Ok(Self(id))
        } else {
            Err(ToolUseIdError(id))
        }
    }

    /// The raw string value of this ID.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ToolUseId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// Error returned when a string doesn't have the `toolu_` prefix required
/// for Anthropic tool-use IDs.
#[derive(Debug, Clone)]
pub struct ToolUseIdError(pub String);

impl fmt::Display for ToolUseIdError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "invalid tool use ID (missing 'toolu_' prefix): {}", self.0)
    }
}

impl std::error::Error for ToolUseIdError {}

/// The set of tools that openclank can provide to the model.
///
/// This is an enum rather than a string because we define the complete tool
/// set ourselves. Using an enum means the compiler ensures we handle every
/// tool in match statements, and there's no risk of typos or invalid tool
/// names sneaking through.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ToolName {
    /// Execute a shell command and return stdout/stderr/exit code.
    Bash,
    /// Read a file's contents, optionally within a line range.
    ReadFile,
    /// Write or overwrite a file with new contents.
    WriteFile,
    /// Apply a search-and-replace edit to a file.
    EditFile,
    /// Find files matching a glob pattern.
    Glob,
    /// Search file contents with a regex pattern.
    Grep,
}

impl ToolName {
    /// The wire name used in the Anthropic API (e.g. "bash", "read_file").
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Bash => "bash",
            Self::ReadFile => "read_file",
            Self::WriteFile => "write_file",
            Self::EditFile => "edit_file",
            Self::Glob => "glob",
            Self::Grep => "grep",
        }
    }

    /// Parse a tool name from the wire format string.
    /// Returns `None` if the name doesn't match any known tool.
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "bash" => Some(Self::Bash),
            "read_file" => Some(Self::ReadFile),
            "write_file" => Some(Self::WriteFile),
            "edit_file" => Some(Self::EditFile),
            "glob" => Some(Self::Glob),
            "grep" => Some(Self::Grep),
            _ => None,
        }
    }
}

impl fmt::Display for ToolName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Who sent a message in the conversation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Role {
    /// A message from the human user.
    User,
    /// A message from the Claude model.
    Assistant,
}

/// A single block of content within a message.
///
/// The Anthropic API represents messages as arrays of content blocks rather
/// than plain strings. This allows a single assistant message to contain
/// text interspersed with tool-use requests. We mirror that structure here
/// so that the conversation can be serialized back to the API without
/// lossy transformation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum ContentBlock {
    /// Plain text content — the most common block type for both user and
    /// assistant messages.
    Text(String),

    /// A tool-use request from the model. The model is asking us to execute
    /// a tool and return the result so it can continue reasoning.
    ToolUse {
        /// Unique identifier for this tool call, generated by the API.
        /// The corresponding [`ContentBlock::ToolResult`] must reference
        /// this same ID so the model can match results to requests.
        id: ToolUseId,
        /// Which tool the model wants to invoke.
        name: ToolName,
        /// The JSON arguments the model wants to pass to the tool.
        input: serde_json::Value,
    },

    /// The result of executing a tool, sent back to the model in the next
    /// request so it can incorporate the output into its reasoning.
    ToolResult {
        /// The [`ToolUseId`] of the tool call this result corresponds to.
        tool_use_id: ToolUseId,
        /// The output from the tool (stdout, file contents, error message, etc.).
        content: String,
        /// Whether the tool execution failed. When true, the model knows to
        /// treat `content` as an error message rather than successful output.
        is_error: bool,
    },
}

/// A finalized, immutable message in the conversation.
///
/// Messages are the permanent record of the conversation. Once created
/// (either directly for user messages, or by finalizing a [`MessageDraft`]
/// for assistant messages), they cannot be modified. This invariant is
/// enforced by the type system: `Message` has no `&mut self` methods that
/// alter content.
#[derive(Debug, Clone, PartialEq)]
pub struct Message {
    /// Who sent this message.
    role: Role,
    /// The content blocks that make up this message. A simple text message
    /// will have a single `ContentBlock::Text`. An assistant message with
    /// tool calls will have a mix of `Text` and `ToolUse` blocks.
    content: Vec<ContentBlock>,
}

impl Message {
    /// Create a message with an explicit role and content blocks.
    /// This is the most general constructor — used when you need to
    /// build messages with tool-use or tool-result blocks, or mixed
    /// content that the convenience constructors (`user`, `assistant`)
    /// don't cover.
    pub fn from_content_blocks(role: Role, content: Vec<ContentBlock>) -> Self {
        Self { role, content }
    }

    /// Create a user message containing a single text block.
    pub fn user(text: &str) -> Self {
        Self {
            role: Role::User,
            content: vec![ContentBlock::Text(text.to_string())],
        }
    }

    /// Create a completed assistant message containing a single text block.
    /// Useful in tests and for constructing mock responses.
    pub fn assistant(text: &str) -> Self {
        Self {
            role: Role::Assistant,
            content: vec![ContentBlock::Text(text.to_string())],
        }
    }

    /// The role (user or assistant) of this message.
    pub fn role(&self) -> &Role {
        &self.role
    }

    /// The content blocks of this message.
    pub fn content(&self) -> &[ContentBlock] {
        &self.content
    }

    /// Extract all text content from this message, concatenated together.
    /// Non-text blocks (tool use, tool results) are skipped. Used for
    /// display in the chat view where text and tool blocks render separately.
    pub fn text(&self) -> String {
        self.content
            .iter()
            .filter_map(|b| match b {
                ContentBlock::Text(t) => Some(t.as_str()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join("")
    }

    /// Create a user-role message containing a single tool result block.
    ///
    /// In the Anthropic API, tool results are sent as user messages with
    /// a `tool_result` content block. The `tool_use_id` must match the
    /// `id` of the original tool-use request so the model can pair them.
    /// The `is_error` flag tells the model whether the tool succeeded or
    /// failed, so it can interpret the content appropriately.
    pub fn from_tool_result(tool_use_id: ToolUseId, content: String, is_error: bool) -> Self {
        Self {
            role: Role::User,
            content: vec![ContentBlock::ToolResult {
                tool_use_id,
                content,
                is_error,
            }],
        }
    }

    /// Return all tool-use blocks in this message, along with their index
    /// in the content array. Each entry is `(index, id, name, input)`.
    /// Used to enumerate pending tool calls that need user approval.
    pub fn tool_uses(&self) -> Vec<(usize, &ToolUseId, ToolName, &serde_json::Value)> {
        self.content
            .iter()
            .enumerate()
            .filter_map(|(i, b)| match b {
                ContentBlock::ToolUse { id, name, input } => Some((i, id, *name, input)),
                _ => None,
            })
            .collect()
    }
}

/// A message that is currently being streamed from the API.
///
/// This is the mutable counterpart to [`Message`]. While the API streams
/// chunks of a response, they are accumulated here. The draft provides
/// `append_text` and `add_tool_use` methods for building up content
/// incrementally.
///
/// Once streaming is complete, call [`MessageDraft::finalize`] to convert
/// the draft into an immutable [`Message`]. This typestate transition is
/// one-way — you cannot go back from `Message` to `MessageDraft`.
#[derive(Debug, Clone)]
pub struct MessageDraft {
    /// The role is always `Assistant` for drafts, since only model responses
    /// are streamed. User messages are created complete.
    role: Role,
    /// The content blocks accumulated so far during streaming.
    content: Vec<ContentBlock>,
}

impl MessageDraft {
    /// Start a new empty assistant message draft for streaming.
    pub fn new_assistant() -> Self {
        Self {
            role: Role::Assistant,
            content: Vec::new(),
        }
    }

    /// The content blocks accumulated so far. Used by the renderer to
    /// display in-progress content while streaming.
    pub fn content(&self) -> &[ContentBlock] {
        &self.content
    }

    /// Extract all text content accumulated so far, concatenated together.
    pub fn text(&self) -> String {
        self.content
            .iter()
            .filter_map(|b| match b {
                ContentBlock::Text(t) => Some(t.as_str()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join("")
    }

    /// Append a text chunk to the draft. If the last content block is
    /// already text, the chunk is appended to it. Otherwise, a new text
    /// block is created. This is the primary method used during streaming
    /// to build up the response incrementally.
    pub fn append_text(&mut self, chunk: &str) {
        match self.content.last_mut() {
            Some(ContentBlock::Text(t)) => t.push_str(chunk),
            _ => self.content.push(ContentBlock::Text(chunk.to_string())),
        }
    }

    /// Add a complete tool-use block to the draft. Tool-use blocks arrive
    /// as a single unit from the streaming API (after the JSON input is
    /// fully parsed), unlike text which arrives in small chunks.
    pub fn add_tool_use(&mut self, id: ToolUseId, name: ToolName, input: serde_json::Value) {
        self.content.push(ContentBlock::ToolUse { id, name, input });
    }

    /// Finalize this draft into an immutable [`Message`]. This consumes
    /// the draft — after calling this, the streaming content is frozen
    /// and no further modifications are possible.
    pub fn finalize(self) -> Message {
        Message {
            role: self.role,
            content: self.content,
        }
    }
}

/// An ordered sequence of messages forming the conversation history.
///
/// The conversation holds all finalized [`Message`]s plus an optional
/// [`MessageDraft`] for the currently-streaming response. When the draft
/// is finalized, it moves into the messages list.
///
/// The full conversation (messages only, not the draft) is serialized and
/// sent to the Anthropic API on each turn so the model has full context.
#[derive(Debug, Clone, Default)]
pub struct Conversation {
    /// Finalized messages in chronological order. User and assistant messages
    /// alternate, with tool-result messages inserted between assistant
    /// turns when the model uses tools.
    pub messages: Vec<Message>,

    /// The currently-streaming assistant response, if any. At most one draft
    /// exists at a time. When streaming completes, this is finalized and
    /// pushed onto `messages`.
    pub draft: Option<MessageDraft>,
}

impl Conversation {
    /// Add a finalized message to the end of the conversation.
    pub fn push(&mut self, msg: Message) {
        self.messages.push(msg);
    }

    /// Start streaming a new assistant response. Panics if a draft already
    /// exists — the caller must finalize or discard the current draft first.
    pub fn start_draft(&mut self) -> &mut MessageDraft {
        assert!(self.draft.is_none(), "cannot start a new draft while one is in progress");
        self.draft = Some(MessageDraft::new_assistant());
        self.draft.as_mut().unwrap()
    }

    /// Finalize the current draft and move it into the message list.
    /// Returns `None` if there is no active draft.
    pub fn finalize_draft(&mut self) -> Option<&Message> {
        if let Some(draft) = self.draft.take() {
            self.messages.push(draft.finalize());
            self.messages.last()
        } else {
            None
        }
    }

    /// Discard the current draft without saving it. Used when the stream
    /// errors out and we don't want to keep partial content.
    pub fn discard_draft(&mut self) {
        self.draft = None;
    }
}
